# Generated by Django 3.2 on 2022-12-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=35)),
                ('date_birth', models.DateField()),
                ('salary', models.CharField(max_length=35)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.manageplacement')),
            ],
        ),
    ]
